# infra/compose.yaml
services:
  mongo:
    image: mongo:7
    container_name: cvtailor-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: cvtailor-backend
    environment:
      PORT: 4000
      MONGODB_URI: mongodb://mongo:27017/cv-tailor
      CORS_ORIGIN: http://localhost:3000

      # LLM Provider config
      LLM_PROVIDER: openai
      OPENAI_API_KEY: YOUR_OPENAI_KEY
      # GEMINI_API_KEY:
      # DEEPSEEK_API_KEY:
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    container_name: cvtailor-frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000/api
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mongo_data:
